title: 電研ブログ
description: 大阪産業大学 文化会 電子計算研究部の公式ブログ。活動報告や制作物、部員による発信をしています。
author: 大阪産業大学 文化会 電子計算研究部
url: "https://osu-denken.github.io"
baseurl: "/blog"
theme: minima
markdown: kramdown
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: 
    - strikethrough
    - autolink
    - table
    - tagfilter
plugins:
  - jekyll-paginate
kramdown:
  input: GFM
  autolink: true
  tables: true
  
paginate: 10
paginate_path: "/page:num/"
